### ISSUE TITLE
Operation with lithium cells

### ISSUE THREAD

**Issue by dewi-ny-je** [Miceuz/PlantWateringAlarm#3]
Since I have multiple plants next to each other I was thinking about powering them with a rechargeable lithium cell.

Would Chirp work with 4.1-3.3 V input? What is the tested operating range?

**Comment by Miceuz** [comment]
Tested operating range is 3.3 to 5V. The circuit is really sensitive to voltage swings, so better add a low drop out regulator to keep it at 3.3V. You can get one in sot-23-5 package with enable pin which you could use to power down all the sensors. Put your I2C pullup resistors on the same regulated 3.3V so that they can get shut down also.

**Comment by dewi-ny-je** [comment]
Thanks for the info. I'm buying some MCP1700-3.0 that should have 1.6 uA quiescent current, to keep things simple.
